### PR TITLE
Updates the dependencies in the mix.exs file and thus allows it to build with Elixir 1.0.5 & Erlang 18.

### PR DESCRIPTION
**Pull request by ghost**
Because it can lead to compilation errors like that that

Or other warnings, such as
httpotion_warning

### CODE REVIEW

**Comment by ghitchens** [comment]
Thanks!

**Comment by ghost** [comment]
I'm glad I could help (^_^)
